services:
  raven1:
    image: ravendb/ravendb-nightly:7.0-ubuntu-latest
    container_name: raven1
    ports:
      - 8081:8080
      - 38881:38888
    environment:
      - RAVEN_SETTINGS={}
      - RAVEN_ARGS=--log-to-console
      - RAVEN_Setup_Mode=None
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
      - RAVEN_PublicServerUrl=http://raven1:8080
      - RAVEN_PublicServerUrl_Tcp=tcp://raven1:38888
      - RAVEN_License_Eula_Accepted=true
      - RAVEN_License_Path=/ravendb/license
    volumes:
      - ./license.json:/ravendb/license
      
  raven2:
    image: ravendb/ravendb-nightly:7.0-ubuntu-latest
    container_name: raven2
    ports:
      - 8082:8080
      - 38882:38888
    environment:
      - RAVEN_SETTINGS={}
      - RAVEN_ARGS=--log-to-console
      - RAVEN_Setup_Mode=None
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
      - RAVEN_PublicServerUrl=http://raven2:8080
      - RAVEN_PublicServerUrl_Tcp=tcp://raven2:38888
      - RAVEN_License_Eula_Accepted=true
      - RAVEN_License_Path=/ravendb/license
    volumes:
      - ./license.json:/ravendb/license
   
  raven3:
    image: ravendb/ravendb-nightly:7.0-ubuntu-latest
    container_name: raven3
    ports:
      - 8083:8080
      - 38883:38888 
    environment:
      - RAVEN_SETTINGS={}
      - RAVEN_ARGS=--log-to-console
      - RAVEN_Setup_Mode=None
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
      - RAVEN_PublicServerUrl=http://raven3:8080
      - RAVEN_PublicServerUrl_Tcp=tcp://raven3:38888
      - RAVEN_License_Eula_Accepted=true
      - RAVEN_License_Path=/ravendb/license
    volumes:
      - ./license.json:/ravendb/license

  client-app:
    image: ravendb-client-app
    container_name: client-app
    pull_policy: never
    restart: no
    profiles:
      - manual
    environment:
      - RAVEN_URLS=http://raven1:8080,http://raven2:8080,http://raven3:8080
      - RAVEN_DATABASE=HighAvailability
